name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: 27 20 * * *
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Run
        run: |
          if [ '${{ secrets.BDUSS }}' != '' ]; then sed -i "s/xxxxx/${{ secrets.BDUSS }}/" tieba.php; fi
          random_time=$((600 % 300))
          echo "等待 ${random_time} 分钟后开始签到"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          php tieba.php
